### ISSUE TITLE
After upgrade of xCode get the following error

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#33]
`/node_modules/react-native-turbolinks/ios/TurbolinksUtils/TurbolinksSession.swift:2:8: Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /node_modules/react-native-turbolinks/ios/Turbolinks.framework/Modules/Turbolinks.swiftmodule/x86_64.swiftmodule`

Swift is set as 4 in the parent project settings no 4.2
I have upgraded react-native-turbolinks

**Comment by lazaronixon** [comment]
Fixed cfd307dfbc7698586ede1333fa50e83d43523ee3

**Comment by nconroy** [comment]
I now get the error: 'React/RCTViewManager.h' file not found

`....../node_modules/react-native-turbolinks/ios/RNTurbolinks-Bridging-Header.h:1:9: error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>

:0: error: failed to emit precompiled header '...../Build/Intermediates.noindex/PrecompiledHeaders/RNTurbolinks-Bridging-Header-swift_16HIP85V7HDX-clang_22NTF7FOJMGSN.pch' for bridging header '..../node_modules/react-native-turbolinks/ios/RNTurbolinks-Bridging-Header.h' `

**Comment by lazaronixon** [comment]
Try clear and build the project.. And you need to replace Turbolinks.framework too and user React-native 0.57... I am working on a compability with 0.58 now...

**Comment by lazaronixon** [comment]
new version https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.6.9

**Comment by RedRoosterMobile** [comment]
I tried updating an existing project with the latest version of react-native-turbolinks. 
I have no luck copying, overwriting, recompiling, celaning, linking, unlink. Just  can't get it to build. It always fails at the link step.
What's the procedure here?

**Comment by lazaronixon** [comment]
Did you upgrade your project with “react-native-git-upgrade 0.57.0” before?
ps: you dont need run react-native link again when updating...
